theme: jekyll-theme-cayman
title: Hongjin (Nicole) Lin 林鸿瑾
description: I am currently a master student in Data Science at the London School of Economics. I am trying to create a home for my fun coursework and personal projects. Would love to hear from you! 
